homework-12 to check
eugene-okulik/st8 pull request #103
Opened 2024-08-15 03:29 UTC by SANTANYN

2024-08-15 15:15 UTC, eugene-okulik requested changes

2024-08-15 15:15 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-12/homework-12_1.py
В задании было:
> Создайте универсальный декоратор

Но с вот такой функцией этот декоратор не справляется:
```python
@finish_text
def example2(ex):
    print(ex)
    return f'ex was {ex}'
```

2024-08-15 15:15 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-12/homework-12_2.py
И этот декоратор - не универсальный. Им тоже невозможно декорировать мою функцию.

2024-08-17 09:10 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-12/homework-12_3.py
> +и он не подсказал, что wrapper нельзя вызывать как функцию внутри wrapper().
Сейчас ты и не вызываешь функцию wrapper нигде, вот оно и работает. Функция wrapper - это шаблон функции, которая в доработанном виде будет возвращена в результате работы декоратора operations. Оно работает просто потому, что ты создал правильную структуру )))

2024-08-17 09:14 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-12/homework-12_2.py
Этот декоратор всё еще не универсальный. Я не могу запустить так
```python
@func_repeat_controller(count=3)
def example2(ex):
    print(ex)
    return f'ex was {ex}'

example2('sdfsdfsdf')
```

2024-08-17 09:19 UTC, SANTANYN commented on homework/mikhail_sorokin/homework-12/homework-12_3.py
> +и он не подсказал, что wrapper нельзя вызывать как функцию внутри wrapper().
Я думал вызывается если использовать этот декроратор - типа если функция помечена декоратором это равноценно вызову функции

2024-08-17 09:22 UTC, SANTANYN commented on homework/mikhail_sorokin/homework-12/homework-12_2.py
а как он справится с этой функцие если у ex нет никакого значения ? она невалидна априори
я добавил для ex какое-то значение выше и твоя функция стала проходить 
В изначальном виде с такой переменной это бесмысленно я ниак не сделаю так чтобы она работала

2024-08-17 09:24 UTC, SANTANYN commented on homework/mikhail_sorokin/homework-12/homework-12_1.py
вот пример как она отрабатывает 
result = 9
finished
None
12
finished
ex was 12

2024-08-17 09:53 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-12/homework-12_3.py
> +и он не подсказал, что wrapper нельзя вызывать как функцию внутри wrapper().
Ну, по сути да, это равноценно вызову функции wrapper, но в ее финальном виде.  
Но здесь же у тебя не просто про вызов wrapper, а про "wrapper нельзя вызывать как функцию внутри wrapper()"

2024-08-17 09:54 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-12/homework-12_3.py
> +и он не подсказал, что wrapper нельзя вызывать как функцию внутри wrapper().
И такого я у тебя не вижу. Возможно, в момент, когда ты спрашивал у чата, такой вызов у тебя был.

2024-08-17 09:57 UTC, SANTANYN commented
да там был вызов до того как комитеул, так не работало, и я долго не мог
понять почему - все же идеально:)
в итоге чат указал на эту проблему и убрал вызов

On Sat, 17 Aug 2024 at 16:54, Eugeny Okulik ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In homework/mikhail_sorokin/homework-12/homework-12_3.py
> <https://github.com/eugene-okulik/st8/pull/103#discussion_r1720750442>:
>
> > +Программа спрашивает у пользователя 2 числа (вне функции)
> +
> +Создайте декоратор, который декорирует функцию calc и управляет тем какая операция будет произведена:
> +
> +если числа равны, то функция calc вызывается с операцией сложения этих чисел
> +если первое больше второго, то происходит вычитание второго из певрого
> +если второе больше первого - деление первого на второе
> +если одно из чисел отрицательное - умножение
> +"""
> +
> +"""декоратор запрашивает числа, затем сравнивает их и выбирает операцию"""
> +
> +# ВНИМАНИЕ!!!!!!!
> +"""
> +Я все сам реализовал но долго не мог понять почему была жалоба на тип данных пока не пошел спрашивать  чат gpt
> +и он не подсказал, что wrapper нельзя вызывать как функцию внутри wrapper().
>
> И такого я у тебя не вижу. Возможно, в момент, когда ты спрашивал у чата,
> такой вызов у тебя был.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eugene-okulik/st8/pull/103#discussion_r1720750442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APEFV3XUYUDGN7KLPYUDOHLZR4MVVAVCNFSM6AAAAABMRPVKF6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBUGA3TONZYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-17 10:45 UTC, SANTANYN commented on homework/mikhail_sorokin/homework-12/homework-12_2.py
Проблема что-ли в том что finished возвращается не последним, а перед
ex was 12 ?

2024-08-19 09:09 UTC, eugene-okulik approved these changes

2024-08-19 09:09 UTC, merged