homework #12 is done
eugene-okulik/st8 pull request #104
Opened 2024-08-15 08:42 UTC by BogdanStepchenko

All 3 tasks were done

2024-08-16 08:38 UTC, eugene-okulik requested changes
Всё хорошо, но давай сделаем универсальными те декораторы, которые нужно сделать универсальными.

2024-08-16 08:38 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_12/2.py
> +            while count < needed_calls:
Обычно повторение несколько раз делают так
```python
for count in range(needed_calls):
```
Тогда и заморочки с этим nonlocal не будет.  
Вообще говоря, почему я не особо рассказываю про области видимости и глобальные переменные. Потому что как только о них узнают, начинает казаться, что ими очень удобно пользоваться и начинают использовать их везде, но это во-первых не рекомендуется, во-вторых, практически всегда структуру кода можно изменить таким образом, что они и не понадобятся.  Существует вероятность где-то в районе 0,01%, что твоему коду действительно нужны эти инструкции.

2024-08-16 08:38 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_12/2.py
> +# как следствие - в параметрах фунцкции при вызове
Это решение делает декоратор не универсальным. Ведь если мы во враппере будем ждать *args и **kwargs, то он станет универсальным и мы сможем достать оттуда (из kwargs) count, если его там указали.

2024-08-16 08:38 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_12/3.py
> +    second = int(input('Please, enter 2nd number: '))
Блин, зачем я вам показал инпут внутри декоратора

2024-08-16 08:38 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_12/3.py
> +print(some_func())
Идея была в том, что здесь вызов будет таким
```python
print(some_func(1, 5))
```

2024-08-16 13:48 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_12/2.py
> +            while count < needed_calls:
Тут согласен, но просто ниже я сделал через range (хоть и запихал ее в map()) - подумал, что не буду делать 2 одинаковых варианта, поэтому через nonlocal тут сделал)

2024-08-16 13:59 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_12/3.py
> +    second = int(input('Please, enter 2nd number: '))
"Ля, смотри как могу" :D

2024-08-16 13:59 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_12/3.py
> +print(some_func())
Поправил)

2024-08-16 13:59 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_12/2.py
> +# как следствие - в параметрах фунцкции при вызове
Поправил)

2024-08-16 14:06 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_12/2.py
> +            while count < needed_calls:
Но сделал, как ты хочешь)

2024-08-16 14:12 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_12/2.py
> +# как следствие - в параметрах фунцкции при вызове
Поправил)

2024-08-17 09:49 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_12/2.py
> +            while count < needed_calls:
После объяснения, мог и не переделывать ))))

2024-08-17 09:51 UTC, eugene-okulik approved these changes

2024-08-17 09:51 UTC, merged