datya/homework_12 is done
eugene-okulik/st8 pull request #110
Opened 2024-08-18 16:26 UTC by Hopenot

2024-08-19 09:43 UTC, eugene-okulik requested changes

2024-08-19 09:43 UTC, eugene-okulik commented on homework/darya_polozkova/homework_12_decorators/hw_12_part_2.py
> +        for i in range(times):
Питон часто нас заставляет создавать переменные, которыми мы не пользуемся, как здесь. В таких ситуациях, таким переменным дают название `_`. Было бы так:
```python
for _ in range(times):
```

2024-08-19 09:43 UTC, eugene-okulik commented on homework/darya_polozkova/homework_12_decorators/hw_12_part_3.py
> +    return wrapper
При этом подходе, функция `calc` вообще не используется. Можешь убрать из нее код - ничего не поменяется. Ты выполняешь арифметическое действие самим декоратором. А нужно, чтобы декоратор только определил с каким знаком функция `calc` должна быть запущена и запустил ее. То есть, в ифах в `operation` должен быть назначен один из знаков: +-*/ а потом этот знак должен быть подставлен в функцию `calc`, которую этот декоратор вызывает.

2024-08-19 10:46 UTC, Hopenot commented on homework/darya_polozkova/homework_12_decorators/hw_12_part_2.py
> +        for i in range(times):
Исправила

2024-08-19 10:47 UTC, Hopenot commented on homework/darya_polozkova/homework_12_decorators/hw_12_part_3.py
> +    return wrapper
Исправила! Спасибо!

2024-08-20 08:23 UTC, eugene-okulik approved these changes

2024-08-20 08:23 UTC, merged