Ivan Emelianov / Homework_12
eugene-okulik/st8 pull request #119
Opened 2024-08-22 15:56 UTC by IvanEmelianov

2024-08-23 08:54 UTC, eugene-okulik requested changes

2024-08-23 08:54 UTC, eugene-okulik commented on homework/ivan_emelianov/Homework_12/Task_2.py
> +            i += 1
Если добавить **kwargs кроме *args, то декоратор станет действительно универсальным
```python
def wrapper(*args, **kwargs):
        i = 1
        while i <= 2:
            func(*args, **kwargs)
            i += 1
```
Ну и ты сделал декоратор, который запускает функцию ровно два раза. А нужно, чтобы можно было ему указать сколько раз нужно эту функцию запустить
```
example('print me', count=2)
example('print me', count=3)
example('print me', count=10)
```

2024-08-26 15:28 UTC, IvanEmelianov commented on homework/ivan_emelianov/Homework_12/Task_2.py
> +            i += 1
Долго мучался с этим, но только понял, как передать country в сам декоратор в таком виде @repeat_me(country=3)

2024-08-27 08:38 UTC, eugene-okulik commented on homework/ivan_emelianov/Homework_12/Task_2.py
> +            i += 1
"Простой" вариант будет выглядеть так
```python
def repeat_me(func):
    def wrapper(*args, **kwargs):
        count = kwargs.pop('count')
        for _ in range(count):
            func(*args, **kwargs)
    return wrapper


@repeat_me
def example(text):
    print(text)


example('print', count=3)
```

2024-08-27 08:38 UTC, eugene-okulik approved these changes

2024-08-27 08:38 UTC, merged