homework_20_is_done
eugene-okulik/st8 pull request #161
Opened 2024-09-15 12:44 UTC by BogdanStepchenko

File for homework 20 was added

2024-09-16 09:56 UTC, eugene-okulik requested changes
Я при запуске программе уже дал все данные, а она у меня что-то спрашивает
![2024-09-16_12-51](https://github.com/user-attachments/assets/5545b757-8abd-47cb-a0a3-75191956bbdb)

2024-09-16 09:56 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_20/1.py
> +        self.repository_root = Path(os.path.dirname(__file__)).parent.parent.parent
Тебе это не нужно. Пользователь вводит полный путь до папки, которую нужно проанализировать. Нужно просто работать с тем, что дал пользователь. Ничего преобразовывать и вычислять не нужно. Идешь по указанному пути и с ним работаешь.

2024-09-16 09:56 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_20/1.py
> +        self.repository_root = Path(os.path.dirname(__file__)).parent.parent.parent
Пользователь может указать любую папку, даже ту, которая не в репозитории.

2024-09-16 09:56 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_20/1.py
> +        self.repository_root = Path(os.path.dirname(__file__)).parent.parent.parent
типа так
![image](https://github.com/user-attachments/assets/8f8c9828-11c5-4cd7-977b-996527bc71d7)

2024-09-16 12:06 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_20/1.py
> +        self.repository_root = Path(os.path.dirname(__file__)).parent.parent.parent
Гугл говорит, что в такой ситуации нужно использовать argparse (ArgumentParser + add_argument).
Если честно впервые это вижу, поэтому, видимо, сперва придётся изучить, как это работает.

И всё еще не понимаю, почему не нужны атрибуты класса, содержащиеся в __init__.

2024-09-17 08:28 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_20/1.py
> +        self.repository_root = Path(os.path.dirname(__file__)).parent.parent.parent
По поводу атрибутов класса - делай пока как понимаешь. Потом с этим разберемся.

2024-09-18 06:25 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_20/1.py
> +        self.repository_root = Path(os.path.dirname(__file__)).parent.parent.parent
Добавил парсинг атрибутов.
Переместил некоторые атрибуты класса внутрь функций.

2024-09-18 08:38 UTC, eugene-okulik requested changes
Отлично. С аргументами разобрался. Теперь разбираемся с путем.

2024-09-18 08:38 UTC, eugene-okulik commented on homework/bogdan_stepchenko/homework_20/1.py
> +        target_folder = os.path.join(self.repository_root, dir_path)
Файлы, которые пользователь отдает этой программе могут быть где угодно на компе. Если я указываю полный путь к папке, то питон, судя по всему, игнорирует этот джоин
![image](https://github.com/user-attachments/assets/185ea1af-10a2-4fda-86ff-88bfec46cd77)
Но если я указываю относительный путь к нужной папке, то перед ее путем зачем-то подставляется путь к корню проекта
![image](https://github.com/user-attachments/assets/8b8d675a-49c9-4c32-ad5a-c1ba3d712f52)
Но нам здесь корень проекта не важен. Файлы могут находиться где угодно на компе. Юзер сам разбирается как правильно указать путь к файлам, которые ему нужно проанализировать  
И если строчку 
```python
target_folder = os.path.join(self.repository_root, dir_path)
```
заменить на 
```python
target_folder = dir_path
```
То все сценарии работают отлично
![image](https://github.com/user-attachments/assets/0dc591d6-c4e3-4780-8f40-fc6c84633f79)

2024-09-18 10:41 UTC, BogdanStepchenko commented on homework/bogdan_stepchenko/homework_20/1.py
> +        target_folder = os.path.join(self.repository_root, dir_path)
Убрал __init__ (вместе с directory_root), а также заменил 
<code>target_folder = os.path.join(self.repository_root, dir_path)</code>
на
<code>target_folder = dir_path</code>

2024-09-19 11:38 UTC, eugene-okulik approved these changes

2024-09-19 11:39 UTC, merged