darya/homework_25_and_26
eugene-okulik/st8 pull request #195
Opened 2024-10-14 08:52 UTC by Hopenot

2024-10-14 12:17 UTC, eugene-okulik requested changes

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/conftest.py
> +def independent_test_create_an_object():
Странное название. Ведь неважно где будет использоваться объект, созданный этой фикстурой

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/conftest.py
> +    created_object = creation_response.json()
Для этого у тебя есть класс, объект которого ты получаешь через фикстуру `independent_test_create_an_object`, можно было воспользоваться функционалом, который ты уже написала, а сейчас у тебя здесь дублирование кода.

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/conftest.py
> +    requests.delete(f'{constants.BASE_URL}/{created_object["id"]}')
ну и для этого у тебя есть класс

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/data/constants.py
> +POSTS_POSTFIX = '/object'
В этой апишке мы с постами не работаем, работаем с объектами.

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/endpoints/create_an_object.py
> +    def independent_test_create_an_object(self, payload=None):
А чо не просто `create_object`?

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    get_object_by_id.check_response_code_is_(200)
В этом тесте нам, по идее, важно проверить, что вернулся объект именно с тем айди, который мы запрашивали.

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    independent_test_create_an_object.independent_test_create_an_object()
А здесь нам важно, что создался объект именно с теми параметрами, с которыми мы его создавали.

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    independent_test_create_an_object.independent_test_create_an_object()
Ну и проверка статуса - тоже обязательная проверка

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    independent_test_delete_an_object.test_independent_delete_an_object(100)
И здесь ты про проверки забыла. Мы ж тестируем. Нужно проверить, что результат соответствует ожидаемому.

2024-10-14 12:17 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    update_object_with_patch.check_response_code_is_(200)
Обычно проверку на статус ставят первой. Так как, если статус вернулся не тот, который ожидалось, то нет смысла дальше что-то проверять.

2024-10-14 18:04 UTC, Hopenot commented on api_tests_dpolozkova/data/constants.py
> +POSTS_POSTFIX = '/object'
в моей голове это звучало, как пост в значении после

2024-10-16 11:09 UTC, Hopenot commented on api_tests_dpolozkova/conftest.py
> +def independent_test_create_an_object():
исправила

2024-10-17 08:32 UTC, eugene-okulik requested changes

2024-10-17 08:32 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    get_object_by_id.check_fields_of_object(test_data.DEFAULT_PAYLOAD)
Нам здесь важно не что объект вернулся с правильно заполненными полями, а что вернулся объект именно с тем айди, который мы запросили. У тебя же тест называется "тест получения объекта по айди", значит главная проверка здесь, что получение по айди работает правильно. А это мы можем проверить сравнив айди полученного объекта с ожидаемым айди. Объектов с одинаковыми данными может быть много, а объект с таким айди - один.

2024-10-17 08:32 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    update_object_with_patch.check_updated_name(name)
В идеале, еще проверять, что остальные поля не изменились и не удалились.

2024-10-17 08:32 UTC, eugene-okulik commented on api_tests_dpolozkova/tests/test_object.py
> +    get_object_by_id.get_object_by_id(1120)
Опа, вдруг хардкод появился. Айди мы должны получать от фикстуры, ведь объекта с этим айди может не оказаться. А тест должен гарантированно работать. Для этого есть предусловия, в которых мы готовим всё к тому, чтобы тест точно отработал.

2024-10-17 09:15 UTC, Hopenot commented on api_tests_dpolozkova/tests/test_object.py
> +    get_object_by_id.get_object_by_id(1120)
Косяк я да, хотела быстрее, а получилось, как всегда

2024-10-17 09:17 UTC, Hopenot commented on api_tests_dpolozkova/tests/test_object.py
> +    get_object_by_id.check_fields_of_object(test_data.DEFAULT_PAYLOAD)
добавила

2024-10-17 16:39 UTC, eugene-okulik approved these changes

2024-10-17 16:39 UTC, merged