ready homework selenium_4
eugene-okulik/st8 pull request #224
Opened 2024-11-13 07:31 UTC by liaushkina83

2024-11-13 20:28 UTC, eugene-okulik requested changes

2024-11-13 20:28 UTC, eugene-okulik commented on homework/margarita_liayshkina/homework_31/test_demoblaze_1.py
> +    go_to_cart_and_verify_product(driver)
У тебя только вот это тест, остальное всё - не тесты. Просто функции. Pytest не сможет это запустить

2024-11-13 20:28 UTC, eugene-okulik commented on homework/margarita_liayshkina/homework_31/test_luma_2.py
> +import time
Вижу, что этим в коде ты не воспользовалась, но не пались - удаляй такие импорты.

2024-11-21 09:29 UTC, liaushkina83 commented on homework/margarita_liayshkina/homework_31/test_luma_2.py
> +import time
Я его использую, пока проверяю, забыла убрать, щас подправила

2024-11-22 06:51 UTC, eugene-okulik requested changes
Что-то особо не изменилось ничего. Всё еще одна функция оформлена как тест и `import time` всё еще на месте. Видимо, что-то не то залилось.

2024-11-22 14:17 UTC, liaushkina83 commented
удалила import time  из файла luma, я туда если честно просто не заглянула, подумала там все ок.  Файл demoblaze тоже подправила.Может еще что-то еще что-то пропустила.

2024-11-23 06:59 UTC, eugene-okulik requested changes
У тебя всё еще один тест и куча питоновских функций. Для того, чтобы pytest мог запустить тесты, функции, в которых находятся эти тесты должны начинаться со слова `test_`

2024-11-28 06:52 UTC, eugene-okulik approved these changes

2024-11-28 06:52 UTC, eugene-okulik commented on homework/margarita_liayshkina/homework_31/test_pop_up_3.py
> +    return result
Тест не должен ничего возвращать. Он просто проверяет. Если он не упал ни на одном ассерте, значит он прошел.

2024-11-28 06:52 UTC, merged

2024-11-28 07:01 UTC, liaushkina83 commented on homework/margarita_liayshkina/homework_31/test_pop_up_3.py
> +    return result
Ну да ,верно, я потом не пользуюсь этими данными дальше.