homework34 to check
eugene-okulik/st8 pull request #228
Opened 2024-11-19 06:05 UTC by SANTANYN

2024-11-19 06:58 UTC, eugene-okulik requested changes

2024-11-19 06:58 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-34/test_first_homework.py
> +        browser = p.chromium.launch(headless=False)
ты настроил всё так, что убил треть функциональности плейрайта. Не нужно ограничивать плейрайт количеством браузеров, в которых он будет запущен. А еще ты жестко зашил режим headless (а я как раз на последнем занятии рассказывал, что этого делать нельзя), теперь твой тест не может быть запущен на серверах.

2024-11-19 06:58 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-34/test_second_task.py
> +        browser = p.chromium.launch(headless=False)
Ну и здесь то же самое. Ты придумал какой-то свой подход. Свои подходы можно придумывать, но они должны быть или лучше или не хуже того, что я показываю.

2024-11-21 06:25 UTC, SANTANYN commented on homework/mikhail_sorokin/homework-34/test_first_homework.py
> +        browser = p.chromium.launch(headless=False)
Я если честно просто поленился нормально сделать, поэтому сделал все на скорую руку. Переделаю тогда.

2024-11-22 06:45 UTC, eugene-okulik requested changes
Всё еще жестко зашит хромиум и режим headless=True

2024-11-30 08:17 UTC, eugene-okulik approved these changes

2024-11-30 08:17 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-34/test_first_homework.py
> +"""
Для того, чтобы не в хедлесс было, при запуске нужно указывать
```
pytest --headed
```
В коде включать хедлесс никак не надо

2024-11-30 08:17 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-34/test_first_homework.py
> +        document.querySelector('#colorChange').style.color === 'rgb(220, 53, 69)' ||
Вот этого `document.querySelector('#colorChange').style.color === 'rgb(220, 53, 69)'` можно было дождаться без всякого джаваскрипта
```python
expect(button).to_have_css('color', 'rgb(220, 53, 69)', timeout=5500)
```

2024-11-30 08:17 UTC, merged