darya/homework_32_project_on_POM_is_done
eugene-okulik/st8 pull request #235
Opened 2024-11-24 09:14 UTC by Hopenot

2024-11-29 07:18 UTC, eugene-okulik requested changes

2024-11-29 07:18 UTC, eugene-okulik commented on selenium_ui_tests_dpolozkova/tests/test_create_account.py
> +    account_page.find_and_click(loc.CREATE_ACCOUNT_BTN)
Тесты не должны ничего знать о локаторах. Нужно, чтобы в тестах было написано, что нужно сделать. А вот в классах у же пусть будет расписано как это нужно сделать и какие локаторы при этом использовать. Эти строчки должны выглядеть так:
```python
    account_page.fill_first_name('Etofirstname')
    account_page.fill_last_name('Etosecondname')
    account_page.fill_email('qatestname12345@qa.com')
    account_page.fill_password('qwerty123!1')
    account_page.fill_confirm_password('qwerty123!1')
    account_page.click_create_account_button
```
Получится, что класс у нас будет содержать все действия, которые нужно совершить на странице, а нам нужно только выбирать какие действия нужны для нашего теста.  
И это касается всех тестов.

2024-11-29 07:18 UTC, eugene-okulik commented on selenium_ui_tests_dpolozkova/pages/eco_friendly_products_page.py
> +        assert self.find(loc.FOUND_ITEM).get_attribute('alt') == 'Fiona Fitness Short'
Fiona Fitness Short - это тестовые данные. Тестовые данные не должны быть зашиты в методы. Эти данные нам нужно указывать в тесте. Метод бы бы такой:\
```python
    def check_found_results(self, text):
        assert self.find(loc.FOUND_ITEM).get_attribute('alt') == text
```

2024-11-29 07:18 UTC, eugene-okulik commented on selenium_ui_tests_dpolozkova/pages/sale_page.py
> +        assert headers[5].text == "You can't have too many tees"
И здесь все тексты - это тестовые данные. Можешь передавать сюда их из теста в виде списка.

2024-11-29 07:18 UTC, eugene-okulik commented on selenium_ui_tests_dpolozkova/pages/sale_page.py
> +        assert breadcrumb.text == "Home Sale"
и Home Sale это тестовые данные. Вот если бы метод назывался check_home_sale_breadcrumb, то можно было бы жестко зашить сюда этот текст.

2024-11-29 07:18 UTC, eugene-okulik commented on selenium_ui_tests_dpolozkova/pages/sale_page.py
> +        assert back.get_attribute('href') == 'https://magento.softwaretestingboard.com/'
А эта проверка в названии метода не объявлена. Эту проверку или нужно вынести в отдельный метод или назвать этот метод так, чтобы было понятно, что в нем еще и это проверяется.

2024-11-29 07:18 UTC, eugene-okulik commented on selenium_ui_tests_dpolozkova/pages/create_account_page.py
> +        assert self.find(loc.EMAIL_ERROR).text == 'Please enter a valid email address (Ex: johndoe@domain.com).'
И здесь тоже тестовые данные нужно убрать в тест

2024-11-30 08:06 UTC, Hopenot commented on selenium_ui_tests_dpolozkova/pages/sale_page.py
> +        assert back.get_attribute('href') == 'https://magento.softwaretestingboard.com/'
назвала check_home_sale_breadcrumb, так как для юзера выглядит, как целый путь, то проверяю составную первую и вторую часть

2024-11-30 08:58 UTC, eugene-okulik approved these changes
:+1:

2024-11-30 08:58 UTC, merged