m.sorokin/homewirk-5
eugene-okulik/st8 pull request #29
Opened 2024-07-14 08:01 UTC by SANTANYN

2024-07-14 09:43 UTC, eugene-okulik requested changes
Здесь с ходу две проблемы:
1. Ты перед выполнение домашнего задания ветку создал не из обновленного main, а, похоже, из ветки предыдущего домашнего задания
2. Все файлы здесь пустые.

2024-07-14 09:44 UTC, SANTANYN commented
Да нет, я точно переключался на main затем стягивал изменения и и создавал новую ветку

2024-07-14 09:48 UTC, SANTANYN commented
Файлы пустые насколько я понимаю из за того что я папку переименовал, а в файлах ничего не делал. Поэтому они подсветились, но без изменений. Если открыть мою ветку в коде, то там все окей.

2024-07-14 09:52 UTC, SANTANYN commented
я перепроверил в пайчарме, ветка создана от origin, а не от старой ветки.
вот скрин пайчарма
<img width="1440" alt="Снимок экрана 2024-07-14 в 16 49 54" src="https://github.com/user-attachments/assets/7ec4b9ee-009b-4ed0-950a-fd3916e30307">

2024-07-14 09:59 UTC, SANTANYN commented
Я гит add делал подтвердив предложение pycharma добавить в отселивание, но он не сделал это почему-то. 
И я каким-то образом запушил пустые файлы, без изменений в них...
Сейчас допушил.

2024-07-14 12:08 UTC, eugene-okulik commented
> Я гит add делал подтвердив предложение pycharma добавить в отслеживание, но он не сделал это почему-то нормально. И я каким-то образом запушил пустые файлы, без изменений в них... Сейчас допушил.

Он тебе предложил сделать git add в тот момент когда они еще пустые были. Если после изменения ты не сделал еще раз git add, то последнее что было у гита - это пустые файлы.

2024-07-14 12:09 UTC, eugene-okulik requested changes

2024-07-14 12:09 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-5/homework5_1.py
> +my_dict['dict'].update({"i am a tuple'": 333})
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `"i am a tuple'"`

2024-07-14 14:38 UTC, SANTANYN commented on homework/mikhail_sorokin/homework-5/homework5_1.py
> +my_dict['dict'].update({"i am a tuple'": 333})
Исправил.
Вообще тут формулировка непонятная, для меня по крайней мере - написал бы прямо добавьте кортэж в словарь  как ключь и любое значение для него.
Я подумал скобки тут просто чтобы выделить.

Пару минут вчитывался и пытался понять в чем разница между твоими двумя формулировками:)

2024-07-15 09:49 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-5/homework5_1.py
> +my_dict['dict'].update({"i am a tuple'": 333})
Это специально, чтобы самому дойти до того, что "так, как-то странно выглядит... А-а-а, это же кортеж с одним элементом, который он показывал."

2024-07-15 09:51 UTC, eugene-okulik approved these changes

2024-07-15 09:51 UTC, eugene-okulik commented on homework/mikhail_sorokin/homework-5/homework5_1.py
> +my_dict['dict'].update({tuple('i am a tuple',): 7})
Можно было просто
```python
my_dict['dict'].update({('i am a tuple',): 7})
```
Бывает, пайчарм ругается на это, но это он от того, что запутался в типах данных.

2024-07-15 09:52 UTC, merged

2024-07-16 07:10 UTC, SANTANYN commented on homework/mikhail_sorokin/homework-5/homework5_1.py
> +my_dict['dict'].update({tuple('i am a tuple',): 7})
Ага, я сперва так и делал. Но pycharm ругался