homework on collections is done
eugene-okulik/st8 pull request #30
Opened 2024-07-14 16:32 UTC by Hopenot

1. Fixed in previous homework comment for pull request
2. Part_1 and part_2 collections homework is done

2024-07-15 09:56 UTC, eugene-okulik requested changes

2024-07-15 09:56 UTC, eugene-okulik commented on homework/darya_polozkova/homework_5_collections/hw_5_part_1.py
> +print(my_dict['tuple'][4])
Так ты распечатала пятый элемент. Не факт, что он последний. Завтра я попрошу (гипотетически) добавить в то, что хранится по ключом tuple еще один элемент и тогда, если ты забудешь здесь подправить, здесь будет распечатываться не последний элемент.

2024-07-15 09:56 UTC, eugene-okulik commented on homework/darya_polozkova/homework_5_collections/hw_5_part_1.py
> +my_dict['dict']['i am a tuple'] = 'this is a value'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-07-16 06:23 UTC, Hopenot commented on homework/darya_polozkova/homework_5_collections/hw_5_part_1.py
> +my_dict['dict']['i am a tuple'] = 'this is a value'
Исправила в коммите [fa66732](https://github.com/eugene-okulik/st8/pull/30/commits/fa6673256dde90f8e1cf9a9099eae114471ccf47)

2024-07-16 08:21 UTC, eugene-okulik approved these changes
:+1:

2024-07-16 08:21 UTC, merged