IvanEmelianov/ homework 5
eugene-okulik/st8 pull request #33
Opened 2024-07-16 11:48 UTC by IvanEmelianov

Немного не понял Задание 2. Нужно было просто распаковать список и все?)

2024-07-16 16:19 UTC, IvanEmelianov commented
Вроде поправил, но не уверен на сколько это правильно)

2024-07-17 08:07 UTC, eugene-okulik requested changes

2024-07-17 08:07 UTC, eugene-okulik commented on homework/ivan_emelianov/Homework_5/Task_1.py
> +my_dict['dist'][('i am a tuple')] = "qwe"
Теперь у тебя ключ всё еще не кортеж с одним элементом, а строка в скобках

2024-07-17 08:59 UTC, IvanEmelianov commented
Вот теперь исправил))

2024-07-17 14:36 UTC, eugene-okulik approved these changes
:+1:

2024-07-17 14:36 UTC, merged