Pashaevilya homework 5
eugene-okulik/st8 pull request #34
Opened 2024-07-16 14:30 UTC by IlyaPashaevQA

:)

2024-07-16 14:36 UTC, eugene-okulik requested changes
Всё отлично, но одну проверку на внимательность не прошел.

2024-07-16 14:36 UTC, eugene-okulik commented on homework/ilya_pashaev/Homework_5/homework5 task1.py
> +my_dict['dict'][('i am a tuple')] = 1000
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка в скобках `('i am a tuple')`

2024-07-16 14:36 UTC, eugene-okulik commented on homework/ilya_pashaev/Homework_5/homework5 task1.py
> +my_dict['dict'][('i am a tuple')] = 1000
А, ну и нужно поправить то, на что руается Линт

2024-07-16 14:44 UTC, IlyaPashaevQA commented
Исправил все линт ошибки

2024-07-17 07:56 UTC, eugene-okulik requested changes

2024-07-17 07:56 UTC, eugene-okulik commented on homework/ilya_pashaev/Homework_5/homework5 task1.py
> +my_dict['dict'][('i am a tuple')] = 1000
> В задании было:
> 
> > добавьте элемент с ключом ('i am a tuple',) и любым значением
> 
> У тебя выполнено как если бы там было
> 
> > добавьте элемент с ключом 'i am a tuple' и любым значением
> 
> `('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка в скобках `('i am a tuple')`

А вот это не поправил

2024-07-26 14:55 UTC, eugene-okulik approved these changes

2024-07-26 14:55 UTC, merged