istrybuk: homework 6 completed
eugene-okulik/st8 pull request #50
Opened 2024-07-21 20:17 UTC by istrybuk

2024-07-22 08:05 UTC, eugene-okulik requested changes

2024-07-22 08:05 UTC, eugene-okulik commented on homework/ivan_strybuk/homework_6/task_1.py
> +split_text_2 = text_2.split(': ')[1]
Если бы заданием было "Найдите в этой строке число и сделайте с ним нужную операцию", то твое решение было бы наиболее оптимальным, но задание было

> С помощью срезов и метода index  или find получите из каждой строки с результатом число, прибавьте к полученному числу 10, результат сложения распечатайте.

А у тебя ни `index` ни `find` ни срезов.

2024-07-22 10:44 UTC, istrybuk commented on homework/ivan_strybuk/homework_6/task_1.py
> +split_text_2 = text_2.split(': ')[1]
![IMG_20240722_134249_edit_79223855028682.jpg](https://github.com/user-attachments/assets/43f5dccb-a006-466c-a41b-162a33730b52)

Так?

2024-07-22 14:39 UTC, eugene-okulik commented on homework/ivan_strybuk/homework_6/task_1.py
> +split_text_2 = text_2.split(': ')[1]
Ну да, что-то вроде этого.  
А чего ты это сразу в пайчарме не делаешь? Он же точно так же распечатает результат.

2024-07-22 15:39 UTC, istrybuk commented on homework/ivan_strybuk/homework_6/task_1.py
> +split_text_2 = text_2.split(': ')[1]
На работе, тут нету пайчарма.

2024-07-23 08:53 UTC, eugene-okulik approved these changes
:+1:

2024-07-23 08:53 UTC, merged