homework_on_conditions is done
eugene-okulik/st8 pull request #52
Opened 2024-07-22 13:56 UTC by Hopenot

2024-07-22 14:55 UTC, eugene-okulik approved these changes

2024-07-22 14:55 UTC, eugene-okulik commented on homework/darya_polozkova/homework_7_conditions/hw_7_part_2.py
> +        print(_)
Переменную называют `_` только в том случае, если ею ни разу не пользуются. Здесь ты этой переменной пользуешься 5 раз, лучше было бы назвать ее, например `x`

2024-07-22 14:55 UTC, eugene-okulik requested changes
Нужно поправить то, на что ругается линт

2024-07-22 17:21 UTC, Hopenot commented
> Нужно поправить то, на что ругается линт

Fixed

2024-07-23 07:09 UTC, Hopenot reviewed
Fixed

2024-07-23 09:10 UTC, eugene-okulik approved these changes

2024-07-23 09:10 UTC, merged