hw_9/i did not like as I almost just stole it from others
eugene-okulik/st8 pull request #74
Opened 2024-07-30 07:40 UTC by Hopenot

Done hw on generators, got idea, but check other solutions

2024-07-30 12:28 UTC, eugene-okulik requested changes
Хм, впервые вижу кражу пустоты )))))  
Это я типа про то, что файл добавился пустой.

2024-07-30 12:32 UTC, eugene-okulik requested changes
Почти отлично, но программа никогда не останавливается.

2024-07-30 12:33 UTC, eugene-okulik commented
ну и линт еще недоволен там чота

2024-07-30 12:51 UTC, Hopenot reviewed
Fixed

2024-07-31 15:07 UTC, eugene-okulik approved these changes

2024-07-31 15:07 UTC, merged